### ISSUE TITLE
egg-xtransit  connect eror  

### ISSUE THREAD

**Issue by minggangLu** [X-Profiler/xtransit-server#4]
we have an egg project and use egg-xtransit to connect to the websocket,the connection will terminate after a few minites，and the logs only have 'websocket client connecting to xxx' , doesn't have ' websocket client has been connected.' ,is it not connect to the ws

_Originally posted by @minggangLu in https://github.com/X-Profiler/xtransit-manager/issues/6#issuecomment-751998325_

**Comment by hyj1991** [comment]
Please check your network and Nginx configurations
