### ISSUE TITLE
koa + ws 架构改为基于 Egg，且支持多进程部署

### ISSUE THREAD

**Issue by hyj1991** [X-Profiler/xtransit-server#6]
目前 koa + ws 的模式，只能单进程部署，也不利于三个服务端框架的统一

**Comment by hyj1991** [comment]
已经完成

**Comment by jlin-z** [comment]
目前这个服务是支持多进程运行时ws链接长期有效保存吗？有说明文件吗

**Comment by hyj1991** [comment]
> 目前这个服务是支持多进程运行时ws链接长期有效保存吗？有说明文件吗

没看懂你的问题，tcp 肯定不可能以任何形式保存下来，这个方案只是通过 ipc 把维持 ws 的进程做成了无状态而已，这样才能支持多进程部署
